image: openjdk:8-jdk

variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - MAVEN_CLI_OPTS mvn clean compile -B

maven-test:
  stage: test
  dependencies:
    - maven-build
  script:
    - $MAVEN_CLI_OPTS mvn test -B