variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-8
  stage: build
  artifacts:
    paths:
    - target/classes/*
  script:
    - mvn clean compile -B

maven-test:
  image: maven:3-jdk-8
  stage: test
  dependencies:
    - maven-build
  artifacts:
    paths:
    - target/surefire-reports/*.txt
  script:
    - mvn test -B