variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn package -B
  artifacts:
    paths:
    - target/site/cobertura/*

pages:
  stage: deploy
  dependencies:
    - maven-test
  script:
    - mv target/site/cobertura/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
