image: maven:3-jdk-8

variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
  - build
  - test
  - deploy

maven-build:
  stage: build
  script:
  - mvn clean -B
  - mvn package -B
  artifacts:
    paths:
    - target/*.jar

maven-test:
  stage: test
  dependencies:
    - maven-build
  coverage: '/coverage line-rate.*?([0-9]{1,3})%/'
  script:
  - mvn cobertura:cobertura -B
  - mvn cobertura:dump-datafile -B
  artifacts:
    paths:
    - target/site/cobertura/*

pages:
  stage: deploy
  dependencies:
    - maven-test
  script:
    - mv target/site/cobertura/ public/
  artifacts:
    paths:
      - public
  only:
    - master
