image: openjdk:8-jdk

stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean compile -B"

maven-test:
  stage: test
  dependencies:
    - maven-build
  script: "mvn test -B"