variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
#  - build
  - test
  - deploy

#maven-build:
#  image: maven:3-jdk-8
#  stage: build
#  artifacts:
#    paths:
#    - target/classes/*
#  script:  mvn clean compile -B

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: mvn cobertura:cobertura -B
  artifacts:
    paths:
    - target/site/cobertura/*

pages:
  stage: deploy
  dependencies:
    - maven-test
  script:
    - mv target/site/cobertura/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
