variables:
  MAVEN_OPTS: -Xmx256m -XX:MaxPermSize=512m

stages:
  - build
  - test

artifacts:
  paths:
    - target/test-classes
    - target/surefire-reports

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean compile -B

maven-test:
  image: maven:3-jdk-8
  stage: test
  dependencies:
    - maven-build
  script:
    - mvn test -B