name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: maven-build
      run: |
        mvn clean -B
        mvn package -B
    - name: maven-test
      run: |
        mvn cobertura:cobertura -B        
        mvn cobertura:dump-datafile -B
    - name: publish-coverage
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: /home/runner/work/kotlin-pro/kotlin-pro/target/site/cobertura/
        GH_PAT: ${{secrets.GH_PAT}}
